homepage: "http://www.pcre.org/"
primary_contact: "philip.hazel@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - memory
  - undefined
architectures:
  - x86_64
  - i386
